import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import clsx from "clsx";
import Image from 'next/image'
import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const classNameBody= clsx(
    geistSans.variable,
    geistMono.variable,
    'relative min-h-screen'
  )
  return (
    <html lang="en">
      <body
        className={classNameBody}
      >
        <Image
          src="/BackgroundPlain.png"
          alt=""
          fill
          className="object-fill -z-10"
          priority
        />
        {children}
      </body>
    </html>
  );
}
